# Site settings
title: BY Blog                    # 你的博客网站标题
SEOTitle: jzy-102 | BY Blog		# SEO 标题
description: "Hey"	   	   # 随便说点，描述一下

# SNS settings      
github_username: jzy-102     # 你的github账号
jianshu_username: jzy  # 你的简书ID。

# Build settings
# paginate: 10              # 一页你准备放几篇文章
